/* VOID MAP 2.5 — advanced client-only map application */
const map = L.map('map', { zoomControl:false, preferCanvas:true }).setView([28.6139,77.2090], 12);
const layers = {
  standard:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}),
  satellite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Tiles © Esri'}),
  dark:L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© OpenStreetMap © CARTO'}),
  terrain:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap contributors'})
};
layers.standard.addTo(map);
let activeLayer='standard', searchMarker=null, userMarker=null, accuracyCircle=null, headingLine=null, routeLayer=null, routeAltLayers=[], poiLayer=L.layerGroup().addTo(map);
let userLocation=null, currentPlace=null, selectedMode='driving', watchId=null, following=false, currentRoute=null, navigationIndex=0, safeTimer=null;
const $=id=>document.getElementById(id);
const els={search:$('searchInput'),suggestions:$('suggestions'),clear:$('clearBtn'),searchBtn:$('searchBtn'),loc:$('locationBtn'),place:$('placeCard'),name:$('placeName'),address:$('placeAddress'),meta:$('placeMeta'),details:$('placeDetails'),save:$('savePlaceBtn'),dir:$('directionsBtn'),share:$('sharePlaceBtn'),dirCard:$('directionsCard'),dist:$('routeDistance'),time:$('routeTime'),arrival:$('routeArrival'),status:$('routeStatus'),steps:$('stepsList'),alts:$('routeAlternatives'),nav:$('navPanel'),nextTurn:$('nextTurn'),nextDistance:$('nextDistance'),toast:$('toast'),weather:$('weatherCard')};
const escapeHTML=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=(msg)=>{els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2800)};
const saved=()=>JSON.parse(localStorage.getItem('voidSavedPlaces')||'[]');
const setSaved=v=>localStorage.setItem('voidSavedPlaces',JSON.stringify(v));
const history=()=>JSON.parse(localStorage.getItem('voidSearchHistory')||'[]');
const setHistory=v=>localStorage.setItem('voidSearchHistory',JSON.stringify(v));
function addHistory(p){let h=history().filter(x=>x.display_name!==p.display_name);h.unshift({name:p.name||p.display_name.split(',')[0],display_name:p.display_name,lat:p.lat,lon:p.lon});setHistory(h.slice(0,12));}
function formatDistance(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(m/10000<1?1:0)} km`}
function formatDuration(sec){let m=Math.max(1,Math.round(sec/60));return m<60?`${m} min`:`${Math.floor(m/60)}h ${m%60?m%60+'m':''}`}
function transportName(m){return ({driving:'Driving',walking:'Walking',cycling:'Cycling'})[m]||'Driving'}
function iconFor(type){return ({restaurant:'🍽️',cafe:'☕',hospital:'🏥',fuel:'⛽',hotel:'🏨',cinema:'🎬',park:'🌳',atm:'🏧',college:'🎓',shopping:'🛍️'})[type]||'📍'}
function selectPlace(p,zoom=true){currentPlace=p;const lat=+p.lat,lon=+p.lon;if(searchMarker)map.removeLayer(searchMarker);searchMarker=L.marker([lat,lon]).addTo(map).bindPopup(`<b>${escapeHTML(p.name||'Place')}</b><br>${escapeHTML(p.display_name||'')}`).openPopup();if(zoom)map.setView([lat,lon],16);els.name.textContent=p.name||p.display_name?.split(',')[0]||'Location';els.address.textContent=p.display_name||'';els.meta.textContent=[p.type,p.address?.city||p.address?.town||p.address?.village].filter(Boolean).join(' • ');els.details.innerHTML=p.rating?`⭐ ${escapeHTML(p.rating)}`:'';els.save.textContent=saved().some(x=>x.display_name===p.display_name)?'★ Saved':'☆ Save';els.place.classList.remove('hidden');addHistory(p);}
async function searchPlaces(q){q=q.trim();if(!q)return;els.suggestions.classList.add('hidden');els.searchBtn.disabled=true;try{const u=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=8&q=${encodeURIComponent(q)}`;const r=await fetch(u,{headers:{Accept:'application/json'}});const d=await r.json();if(!d.length){toast('No places found');return}selectPlace(d[0]);}catch(e){console.error(e);toast('Search is temporarily unavailable')}finally{els.searchBtn.disabled=false}}
let suggestTimer;els.search.addEventListener('input',()=>{els.clear.classList.toggle('hidden',!els.search.value);clearTimeout(suggestTimer);const q=els.search.value.trim();if(q.length<3){els.suggestions.classList.add('hidden');return}suggestTimer=setTimeout(async()=>{try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&q=${encodeURIComponent(q)}`);const d=await r.json();els.suggestions.innerHTML=d.map((p,i)=>`<button class="suggestion" data-i="${i}">📍 <span>${escapeHTML(p.display_name)}</span></button>`).join('');els.suggestions.classList.toggle('hidden',!d.length);els.suggestions.querySelectorAll('.suggestion').forEach((b,i)=>b.onclick=()=>{selectPlace(d[i]);els.search.value=d[i].display_name;els.suggestions.classList.add('hidden')});}catch{}} ,300)});
els.search.addEventListener('keydown',e=>{if(e.key==='Enter')searchPlaces(els.search.value)});els.searchBtn.onclick=()=>searchPlaces(els.search.value);els.clear.onclick=()=>{els.search.value='';els.suggestions.classList.add('hidden')};
function locate(){if(!navigator.geolocation)return toast('Geolocation is not supported');els.loc.textContent='⌖ Locating…';if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=navigator.geolocation.watchPosition(updateLocation,err=>{toast(err.code===1?'Location permission denied':'Unable to get location');els.loc.textContent='⌖ My location'},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});}
function updateLocation(pos){const {latitude:lat,longitude:lon,accuracy,heading}=pos.coords;userLocation={lat,lon,accuracy,heading};if(!userMarker){userMarker=L.marker([lat,lon],{icon:L.divIcon({className:'user-dot-wrap',html:'<div class="user-dot"></div>',iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map)}else userMarker.setLatLng([lat,lon]);if(!accuracyCircle)accuracyCircle=L.circle([lat,lon],{radius:accuracy||20,color:'#4285f4',fillColor:'#4285f4',fillOpacity:.08,weight:1}).addTo(map);else accuracyCircle.setLatLng([lat,lon]).setRadius(accuracy||20);if(Number.isFinite(heading)){const a=heading*Math.PI/180;const end=[lat+Math.cos(a)*0.0007,lon+Math.sin(a)*0.0007];if(!headingLine)headingLine=L.polyline([[lat,lon],end],{color:'#4285f4',weight:4}).addTo(map);else headingLine.setLatLngs([[lat,lon],end])}if(following)map.setView([lat,lon],Math.max(map.getZoom(),16),{animate:false});els.loc.textContent='⌖ My location';if(currentPlace&&els.dirCard.classList.contains('hidden')===false)calculateRoute();}
els.loc.onclick=()=>{locate();following=true;if(userLocation)map.setView([userLocation.lat,userLocation.lon],16)};$('recenterBtn').onclick=()=>{if(userLocation){following=true;map.setView([userLocation.lat,userLocation.lon],16)}else locate()};map.on('dragstart',()=>following=false);
function changeLayer(name){Object.values(layers).forEach(l=>map.removeLayer(l));layers[name].addTo(map);activeLayer=name;document.querySelectorAll('input[name=baseLayer]').forEach(x=>x.checked=x.value===name);document.body.classList.toggle('map-dark',name==='dark')}
document.querySelectorAll('input[name=baseLayer]').forEach(x=>x.onchange=()=>changeLayer(x.value));$('satelliteBtn').onclick=()=>changeLayer(activeLayer==='satellite'?'standard':'satellite');$('darkModeBtn').onclick=()=>changeLayer(activeLayer==='dark'?'standard':'dark');$('zoomIn').onclick=()=>map.zoomIn();$('zoomOut').onclick=()=>map.zoomOut();$('fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();
function openPanel(id){$(id).classList.remove('hidden')}function closePanel(id){$(id).classList.add('hidden')}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closePanel(b.dataset.close));$('exploreBtn').onclick=()=>openPanel('explorePanel');$('layersBtn').onclick=()=>openPanel('layersPanel');$('savedBtn').onclick=()=>{renderSaved();openPanel('savedPanel')};$('historyBtn').onclick=()=>{renderHistory();openPanel('historyPanel')};
async function nearby(type){if(!userLocation){locate();toast('Allow location, then try again');return}const tags={restaurant:'amenity=restaurant',cafe:'amenity=cafe',hospital:'amenity=hospital',fuel:'amenity=fuel',hotel:'tourism=hotel',cinema:'amenity=cinema',park:'leisure=park',atm:'amenity=atm',college:'amenity=college',shopping:'shop'};const tag=tags[type]||'amenity';const q=`[out:json][timeout:20];(node[${tag}](around:5000,${userLocation.lat},${userLocation.lon});way[${tag}](around:5000,${userLocation.lat},${userLocation.lon});relation[${tag}](around:5000,${userLocation.lat},${userLocation.lon}););out center tags;`;try{toast(`Finding ${type}…`);const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q});const d=await r.json();poiLayer.clearLayers();const items=d.elements.slice(0,80);items.forEach(el=>{const lat=el.lat??el.center?.lat,lon=el.lon??el.center?.lon;if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const name=el.tags?.name||type[0].toUpperCase()+type.slice(1);L.marker([lat,lon],{icon:L.divIcon({className:'poi-icon',html:iconFor(type),iconSize:[28,28],iconAnchor:[14,14]})}).bindPopup(`<b>${escapeHTML(name)}</b><br>${escapeHTML(type)}`).addTo(poiLayer).on('click',()=>selectPlace({name,display_name:name,lat,lon,type},false));});if(items.length)map.setView([userLocation.lat,userLocation.lon],14);toast(`${items.length} ${type} places found`)}catch(e){console.error(e);toast('Nearby search failed — try again')}}
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>nearby(b.dataset.cat));
function routeUrl(mode,a,b){return `https://router.project-osrm.org/route/v1/${mode}/${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=true&alternatives=true&annotations=true`}
async function calculateRoute(){if(!userLocation||!currentPlace)return;els.dirCard.classList.remove('hidden');els.status.textContent=`Finding ${transportName(selectedMode).toLowerCase()} routes…`;els.steps.innerHTML='';els.alts.innerHTML='';routeLayer&&map.removeLayer(routeLayer);routeAltLayers.forEach(x=>map.removeLayer(x));routeAltLayers=[];const start={lat:userLocation.lat,lon:userLocation.lon},end={lat:+currentPlace.lat,lon:+currentPlace.lon};try{const r=await fetch(routeUrl(selectedMode,start,end));const d=await r.json();if(d.code!=='Ok'||!d.routes?.length)throw new Error('No route');currentRoute=d.routes[0];routeLayer=L.geoJSON(currentRoute.geometry,{style:{color:'#4285f4',weight:7,opacity:.9}}).addTo(map);d.routes.slice(1,3).forEach((rt,i)=>{const l=L.geoJSON(rt.geometry,{style:{color:'#8ab4f8',weight:5,opacity:.6,dashArray:'8 8'}}).addTo(map);routeAltLayers.push(l);const b=document.createElement('button');b.className='alt-route';b.innerHTML=`Alternative ${i+1}<b>${formatDuration(rt.duration)}</b><span>${formatDistance(rt.distance)}</span>`;b.onclick=()=>{routeLayer&&map.removeLayer(routeLayer);routeAltLayers.forEach(x=>map.removeLayer(x));routeAltLayers=[];routeLayer=L.geoJSON(rt.geometry,{style:{color:'#4285f4',weight:7}}).addTo(map);currentRoute=rt;renderRoute(rt)};els.alts.appendChild(b)});renderRoute(currentRoute);map.fitBounds(routeLayer.getBounds(),{padding:[80,80]});}catch(e){console.error(e);els.status.textContent='No route found for this mode.'}}
function renderRoute(rt){els.dist.textContent=formatDistance(rt.distance);els.time.textContent=formatDuration(rt.duration);els.routeFrom.textContent='Your location';els.routeTo.textContent=currentPlace?.name||'Destination';const arrival=new Date(Date.now()+rt.duration*1000);els.arrival.textContent=arrival.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});els.status.textContent=`${transportName(selectedMode)} route ready`;els.steps.innerHTML=(rt.legs?.[0]?.steps||[]).map((s,i)=>`<div class="step"><span>${i+1}</span><div><b>${escapeHTML(s.name||'Unnamed road')}</b><small>${escapeHTML(s.maneuver?.instruction||s.maneuver?.type||'Continue')} • ${formatDistance(s.distance)}</small></div></div>`).join('')||'<div class="muted">Turn-by-turn details unavailable for this route.</div>';}
document.querySelectorAll('.transport-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.transport-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedMode=b.dataset.mode;calculateRoute()});els.dir.onclick=()=>{if(!userLocation){toast('Tap My location first');locate();return}calculateRoute()};document.querySelectorAll('[data-close="directionsCard"]').forEach(b=>b.onclick=()=>closePanel('directionsCard'));
$('startNavBtn').onclick=()=>{if(!currentRoute)return;navigationIndex=0;els.nav.classList.remove('hidden');updateNavigation();if(userLocation)map.setView([userLocation.lat,userLocation.lon],18)};$('stopNavBtn').onclick=()=>els.nav.classList.add('hidden');function updateNavigation(){const steps=currentRoute?.legs?.[0]?.steps||[];const s=steps[navigationIndex];if(!s){els.nextTurn.textContent='You have arrived';els.nextDistance.textContent='';return}els.nextTurn.textContent=s.maneuver?.instruction||s.name||'Continue';els.nextDistance.textContent=formatDistance(s.distance)}
$('googleRouteBtn').onclick=()=>{if(!currentPlace)return;const url=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(currentPlace.lat+','+currentPlace.lon)}&travelmode=${selectedMode==='cycling'?'bicycling':selectedMode}`;window.open(url,'_blank','noopener')};els.share.onclick=()=>{if(!currentPlace)return;const u=`${location.href.split('#')[0]}#place=${encodeURIComponent(currentPlace.lat)},${encodeURIComponent(currentPlace.lon)}`;navigator.share?navigator.share({title:currentPlace.name||'VOID Map place',text:currentPlace.display_name,url:u}):navigator.clipboard?.writeText(u).then(()=>toast('Share link copied'))};
els.save.onclick=()=>{if(!currentPlace)return;let a=saved();if(a.some(x=>x.display_name===currentPlace.display_name)){toast('Already saved');return}a.unshift({name:currentPlace.name,display_name:currentPlace.display_name,lat:currentPlace.lat,lon:currentPlace.lon});setSaved(a.slice(0,50));els.save.textContent='★ Saved';toast('Place saved')};
function renderSaved(){const a=saved();$('savedList').innerHTML=a.length?a.map((p,i)=>`<button class="list-item" data-i="${i}">★ <span><b>${escapeHTML(p.name||'Place')}</b><small>${escapeHTML(p.display_name)}</small></span></button>`).join(''):'<p class="muted">No saved places yet.</p>';document.querySelectorAll('#savedList .list-item').forEach(b=>b.onclick=()=>{selectPlace(a[+b.dataset.i]);closePanel('savedPanel')})}function renderHistory(){const a=history();$('historyList').innerHTML=a.length?a.map((p,i)=>`<button class="list-item" data-i="${i}">◷ <span><b>${escapeHTML(p.name)}</b><small>${escapeHTML(p.display_name)}</small></span></button>`).join(''):'<p class="muted">No searches yet.</p>';document.querySelectorAll('#historyList .list-item').forEach(b=>b.onclick=()=>{selectPlace(a[+b.dataset.i]);closePanel('historyPanel')})}$('clearHistory').onclick=()=>{setHistory([]);renderHistory()};
async function loadWeather(){const p=userLocation||{lat:map.getCenter().lat,lon:map.getCenter().lng};try{const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.lat}&longitude=${p.lon}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m`);const d=await r.json();els.weather.textContent=`🌤️ ${Math.round(d.current.temperature_2m)}°C • Feels ${Math.round(d.current.apparent_temperature)}°C • Wind ${Math.round(d.current.wind_speed_10m)} km/h`; }catch{els.weather.textContent='Weather unavailable'}}
$('exploreBtn').addEventListener('click',loadWeather);map.on('moveend',()=>{if(!$('weatherCard').classList.contains('hidden'))loadWeather()});
$('trafficToggle').onchange=e=>{if(e.target.checked)toast('Traffic-style overlay enabled. Live traffic needs a traffic provider key.');else toast('Traffic overlay off')};
$('plannerBtn').onclick=()=>{openPanel('plannerPanel');$('planPlace').value=currentPlace?.name||'';if(!$('planDate').value){const d=new Date(Date.now()+86400000);$('planDate').value=d.toISOString().slice(0,10)}};
$('halfwayBtn').onclick=()=>{if(!userLocation||!currentPlace){toast('Set your location and a destination first');return}const lat=(userLocation.lat+ +currentPlace.lat)/2,lon=(userLocation.lon+ +currentPlace.lon)/2;map.setView([lat,lon],14);L.marker([lat,lon]).addTo(poiLayer).bindPopup('❤️ Suggested halfway point').openPopup();$('planResult').textContent='Suggested halfway point shown on the map.'};
$('sharePlanBtn').onclick=()=>{const txt=`❤️ VOID date plan\n${$('planPlace').value||'Meeting place'}\n${$('planDate').value||''} ${$('planTime').value||''}`;navigator.share?navigator.share({title:'VOID date plan',text:txt}):navigator.clipboard?.writeText(txt).then(()=>toast('Plan copied'))};
$('safeModeBtn').onclick=()=>{if(safeTimer){clearInterval(safeTimer);safeTimer=null;$('safeModeBtn').textContent='🛡️ Safe mode';$('planResult').textContent='Safe mode stopped.';return}let mins=60;safeTimer=setInterval(()=>{mins--;if(mins<=0){clearInterval(safeTimer);safeTimer=null;$('safeModeBtn').textContent='🛡️ Safe mode';$('planResult').textContent='Safe mode ended.'}},60000);$('safeModeBtn').textContent='🛡️ Safe mode active';$('planResult').textContent='Safe mode is active for 60 minutes. Location is not shared automatically.'};
(function loadHash(){const m=location.hash.match(/place=([^&]+)/);if(m){const [lat,lon]=decodeURIComponent(m[1]).split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lon)){selectPlace({name:'Shared location',display_name:`${lat.toFixed(5)}, ${lon.toFixed(5)}`,lat,lon},true)}}})();
map.on('click',e=>{following=false});
loadWeather();
